name: Python package

on:
  push:
    paths:
      - 's2d2/**'
      - 'tests/**'
      - setup.py
      - pyproject.toml
      - environment.yml
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] #, 'macos-latest']
        python-version: ['3.10'] #, '3.9', '3.8']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          mamba-version: "*"
          activate-environment: s2d2
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install the library
        run: |
          pip install -e .[test]
      - name: Test
        run: |
          pytest

  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev]
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort
