name: documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          environment-file: environment.yml
          mamba-version: "*"
          activate-environment: s2d2
      - name: Python info
        shell: bash -el {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        shell: bash -el {0}
        run: python -m pip install .[docs]
      - name: Build documentation
        shell: bash -el {0}
        run: make coverage doctest html
        working-directory: docs
